# Generated by Django 4.0.5 on 2022-06-13 11:13

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_alter_category_options_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default=2, upload_to=pathlib.PurePosixPath('/home/emcode/www/django-projects/news')),
            preserve_default=False,
        ),
    ]
